/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as PictureRouteImport } from './routes/picture'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PictureRoute = PictureRouteImport.update({
  id: '/picture',
  path: '/picture',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dossier': typeof DossierRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/nutrition': typeof NutritionRoute
  '/picture': typeof PictureRoute
  '/timeline': typeof TimelineRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dossier': typeof DossierRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/nutrition': typeof NutritionRoute
  '/picture': typeof PictureRoute
  '/timeline': typeof TimelineRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dossier': typeof DossierRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/nutrition': typeof NutritionRoute
  '/picture': typeof PictureRoute
  '/timeline': typeof TimelineRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dossier'
    | '/home'
    | '/journey'
    | '/nutrition'
    | '/picture'
    | '/timeline'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dossier'
    | '/home'
    | '/journey'
    | '/nutrition'
    | '/picture'
    | '/timeline'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/dossier'
    | '/home'
    | '/journey'
    | '/nutrition'
    | '/picture'
    | '/timeline'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DossierRoute: typeof DossierRoute
  HomeRoute: typeof HomeRoute
  JourneyRoute: typeof JourneyRoute
  NutritionRoute: typeof NutritionRoute
  PictureRoute: typeof PictureRoute
  TimelineRoute: typeof TimelineRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picture': {
      id: '/picture'
      path: '/picture'
      fullPath: '/picture'
      preLoaderRoute: typeof PictureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DossierRoute: DossierRoute,
  HomeRoute: HomeRoute,
  JourneyRoute: JourneyRoute,
  NutritionRoute: NutritionRoute,
  PictureRoute: PictureRoute,
  TimelineRoute: TimelineRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
